### ISSUE TITLE
sickrage send my torrent from jackett to my sabnzb 

### ISSUE THREAD

**Issue by maxcore** [SickRage/SickRage#4132]
i use jackett : 
When sickrage grab episode from jackett sickrage sent to sabnzb and not at my rtorrent i have this bug only today .. Why ?

Branch/Commit:master
OS:unraid
What you did:
What happened:
What you expected:
Logs:
```
2017-11-10 16:08:41 DEBUG SEARCHQUEUE-MANUAL-71663 :: Transaction with 0 queries executed
2017-11-10 16:08:41 INFO SEARCHQUEUE-MANUAL-71663 :: Pushover notification successful.
2017-11-10 16:08:41 DEBUG SEARCHQUEUE-MANUAL-71663 :: Pushover API KEY in use: ******************************
2017-11-10 16:08:41 DEBUG SEARCHQUEUE-MANUAL-71663 :: Sending notification for Les Simpson - 28x01 - Monty Burns' Fleeing Circus - 720p WEB-DL from Ethor
2017-11-10 16:08:41 DEBUG SEARCHQUEUE-MANUAL-71663 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Les Simpson - 28x01 - Monty Burns' Fleeing Circus - 720p WEB-DL
2017-11-10 16:08:41 DEBUG SEARCHQUEUE-MANUAL-71663 :: 71663: Not creating SQL queue - record is not dirty
2017-11-10 16:08:41 DEBUG SEARCHQUEUE-MANUAL-71663 :: Checking if we should stop searching for a better quality for for episode The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS
2017-11-10 16:08:39 DEBUG SEARCHQUEUE-MANUAL-71663 :: Result text from SAB: {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_NuJCKg']}
2017-11-10 16:08:38 INFO SEARCHQUEUE-MANUAL-71663 :: Sending NZB to SABnzbd
2017-11-10 16:08:38 INFO SEARCHQUEUE-MANUAL-71663 :: Downloading The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS from Ethor
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Checking if we should keep searching after we've found The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Picked The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS as the best
2017-11-10 16:08:38 INFO SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Quality of The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS is 720p WEB-DL
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Picking the best result out of [u'The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS']
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: The highest quality of any match is 720p WEB-DL
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Single episode result.
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Found result The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS at http://192.168.2.124:9117/dl/ethor/?jackett_apikey=r0smrc2ghhijdjsfa0zkghwcvgjtytep&path=b2VlZXlWOUsvd1I0amZuYjQxYjBqZmJWVy9xbGxwOGZEK0JiWFMwWU5xbzJZblNzNnZNcW5xRmZYSGcvcmpzSlhSNHpPUEdPV1A1d2NwaUVINjcxcS80WXhCcDhSMkd1cUZjakdpQXRtQUplYkc2SVozYnlSVGo2VDJMZklzaDRZU2VrR3BNWDhUODdPVlB2VDRLNUhUK2pPWnpUVFNGV2g2Y0p5MEN3U0xUcDRpNms2Qmp4NUI1QkJuOUcrOFpkNEFkcTlHV2xQT2s2SkROT0daRWhZUTc1MGNoMm1ueGRwc3h2VFJ5Rm5sZEFuUEY1Z1U2WmJBSWxkQTk5QkFxbGlwaEFTRVNnZGxuK3FENGZBaFF4ejlLOVdkblJST0VkV1A1bkthelIrdjBQcUZvZlhaZklrdk81LzhGM3c3TThUUWpsaVhuaUs1U3BqVnJKN2JZSVZnPT01&file=The+Simpsons+S28E01+FRENCHQC+720p+WEBRiP+H264-ZELLERS
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Usually ignoring found result, but forced search allows the quality, getting found result for Les Simpson S28E01 with quality 720p WEB-DL
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Any,Best = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ 720p WEB-DL ]
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Using cached parse result for: The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS
2017-11-10 16:08:38 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: GET URL: http://192.168.2.124:9117/api/v2.0/indexers/ethor/results/torznab/api?apikey=**********&season=28&maxage=2500&cat=5040%2C5030&q=The+Simpsons+S28E01&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]
2017-11-10 16:08:35 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Search string: The Simpsons S28E01
2017-11-10 16:08:35 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: GET URL: http://192.168.2.124:9117/api/v2.0/indexers/ethor/results/torznab/api?apikey=**********&season=28&maxage=2500&cat=5040%2C5030&q=Les+Simpson+S28E01&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]
2017-11-10 16:08:32 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Search string: Les Simpson S28E01
2017-11-10 16:08:32 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Search Mode: Episode
2017-11-10 16:08:32 INFO SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Performing episode search for Les Simpson
2017-11-10 16:08:32 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Freedom-HD] :: GET URL: http://192.168.2.124:9117/api/v2.0/indexers/freedomhd/results/torznab/api?apikey=**********&season=28&maxage=2500&cat=5030%2C5040&q=The+Simpsons+S28E01&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]
2017-11-10 16:08:29 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Freedom-HD] :: Search string: The Simpsons S28E01
2017-11-10 16:08:29 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Freedom-HD] :: GET URL: http://192.168.2.124:9117/api/v2.0/indexers/freedomhd/results/torznab/api?apikey=**********&season=28&maxage=2500&cat=5030%2C5040&q=Les+Simpson+S28E01&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]
2017-11-10 16:08:27 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Freedom-HD] :: Search string: Les Simpson S28E01
2017-11-10 16:08:27 DEBUG SEARCHQUEUE-MANUAL-71663 :: [Freedom-HD] :: Search Mode: Episode
2017-11-10 16:08:26 INFO SEARCHQUEUE-MANUAL-71663 :: [Freedom-HD] :: Performing episode search for Les Simpson
```

**Comment by markolonius** [comment]
I have same problem just started. On latest linuxserver/sickrage docker & linuxserver/jackett docker updated to latest versions.

```
2017-11-12 16:17:11 INFO SEARCHQUEUE-MANUAL-323843 :: Saved result to Bill.Nye.Saves.the.World.S01E02.480p.x264-mSD.nzb 
2017-11-12 16:17:10 INFO SEARCHQUEUE-MANUAL-323843 :: Downloading a result from jackett at http://0.0.0.0:9117/jackett/dl/iptorrents/jackett_apikey=dqf80ep4m86nqlzo0umfaxxzxn24sw3r&path=RS9FMkxuRTVqVUxJdlRORkpTTlNaRUlTbUVZOU9CdEJiU1hrV2VZU0ZkZ0lwd3BiN3pKU0NHUXhNOGRpeCtRUnBSZ0RaWlhRYjdya0ZtTXNqQ1FHWklHbW1oand2eG0zNWs4MUdZeFg1dEk4MmJVYW9OdEk2TlNkMVF4Y0N6c3JHN3dQSGMxd0YrenZmMWVYbnJwQU5Remt2R1ZJZ0E3WHMvenBiRXdWcHZGcFBNRXdKSUZRVXVaakdRVzd4cFFuTkt2a2hqRURRMVg3eTB3ajBCTkxRZkZpNWZZMU0wemxiNk5hUnJMSVBqMzJQVmlCRGtLc0RWR1hSdFZVTTFBd0NLZ1p6RVprRUxrbWdTMHJqc296V0h3QjFUN1FaTWpRZTduemJjbGRlb2I2VUc0ZHdVMFZyaFNTL29BM1NIcjZFRVhqN3J4Qk5kcVZnKzY1dGFsWG1Bb3Y0dXczZnhjdTJLQk9sWFh2bjU0UnFUcElocGxVMTR6TERlZDg4VlNYa0RIQUlCK2NVbTUxR3BGeGJXdUJPM3VIdDM4WEVsKzlwQzFxTDJwVVg4bz01&file=Bill+Nye+Saves+the+World+S01E02+480p+x264-mSD
```

**Comment by maxcore** [comment]
Exactly the same a torrent file rename.nzb

**Comment by maxcore** [comment]
@kaso17 

You have this bug ?

**Comment by kaso17** [comment]
On jackett we recently (starting with version v0.8.396) changed the usage of the file argument, it now only contains the basename (no extension).
From your log:
`DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Found result The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS at http://192.168.2.124:9117/dl/ethor/?jackett_apikey=r0smrc2ghhijdjsfa0zkghwcvgjtytep&path=b2VlZXlWOUsvd1I0amZuYjQxYjBqZmJWVy9xbGxwOGZEK0JiWFMwWU5xbzJZblNzNnZNcW5xRmZYSGcvcmpzSlhSNHpPUEdPV1A1d2NwaUVINjcxcS80WXhCcDhSMkd1cUZjakdpQXRtQUplYkc2SVozYnlSVGo2VDJMZklzaDRZU2VrR3BNWDhUODdPVlB2VDRLNUhUK2pPWnpUVFNGV2g2Y0p5MEN3U0xUcDRpNms2Qmp4NUI1QkJuOUcrOFpkNEFkcTlHV2xQT2s2SkROT0daRWhZUTc1MGNoMm1ueGRwc3h2VFJ5Rm5sZEFuUEY1Z1U2WmJBSWxkQTk5QkFxbGlwaEFTRVNnZGxuK3FENGZBaFF4ejlLOVdkblJST0VkV1A1bkthelIrdjBQcUZvZlhaZklrdk81LzhGM3c3TThUUWpsaVhuaUs1U3BqVnJKN2JZSVZnPT01&file=The+Simpsons+S28E01+FRENCHQC+720p+WEBRiP+H264-ZELLERS`
Before it was `DEBUG SEARCHQUEUE-MANUAL-71663 :: [Ethor] :: Found result The.Simpsons.S28E01.FRENCHQC.720p.WEBRiP.H264-ZELLERS at http://192.168.2.124:9117/dl/ethor/?jackett_apikey=r0smrc2ghhijdjsfa0zkghwcvgjtytep&path=b2VlZXlWOUsvd1I0amZuYjQxYjBqZmJWVy9xbGxwOGZEK0JiWFMwWU5xbzJZblNzNnZNcW5xRmZYSGcvcmpzSlhSNHpPUEdPV1A1d2NwaUVINjcxcS80WXhCcDhSMkd1cUZjakdpQXRtQUplYkc2SVozYnlSVGo2VDJMZklzaDRZU2VrR3BNWDhUODdPVlB2VDRLNUhUK2pPWnpUVFNGV2g2Y0p5MEN3U0xUcDRpNms2Qmp4NUI1QkJuOUcrOFpkNEFkcTlHV2xQT2s2SkROT0daRWhZUTc1MGNoMm1ueGRwc3h2VFJ5Rm5sZEFuUEY1Z1U2WmJBSWxkQTk5QkFxbGlwaEFTRVNnZGxuK3FENGZBaFF4ejlLOVdkblJST0VkV1A1bkthelIrdjBQcUZvZlhaZklrdk81LzhGM3c3TThUUWpsaVhuaUs1U3BqVnJKN2JZSVZnPT01&file=The+Simpsons+S28E01+FRENCHQC+720p+WEBRiP+H264-ZELLERS.torrent`

If sickrage is using the jacket internal file parameter for the torrent/nzb decision I suggest you change it to using the corresponding HTTP headers (Content-Type).

Example headers:
```Content-Type: application/x-bittorrent
Content-Disposition: attachment; filename="The Simpsons S28E01 FRENCHQC 720p WEBRiP H264-ZELLERS.torrent"```

**Comment by Voooo** [comment]
I have the same issue. Sickrage/Jackett/Torrentday.
What ends up in the client is not a .torrent. I can't see the end but it's most likely a .nzb
To long to paste it but i starts with jackett_apikey=XXXXXXXX instead of the show-name.

![jackett](https://user-images.githubusercontent.com/19846326/32744396-a07d11c4-c8af-11e7-8830-484ff3f74f14.PNG)

**Comment by maxcore** [comment]
So sickrage need update this change from jackett

**Comment by Voooo** [comment]
I don't know who does what, I think it was Jackett that made the change some days ago that "broke this."
Hopefully there will be a fix. Maybe it's possible to download a previous version of Jackett and stop the autoupdate feature?

**Comment by maxcore** [comment]
Not for me am with unraid but if you use synology stop de service download old version and up to your synology and restart

**Comment by Voooo** [comment]
Downgraded to Jackett v0.8.355 and disabled autoupdate in Jackett GUI and it works like normal now.

**Comment by maxcore** [comment]
@miigotu you can help pls ..

**Comment by kaso17** [comment]
@Voooo thank you for clarifying, definitely looks like sickrage is trying to parse the filename from the URL instead of the Content-Disposition header.

This change was introduced to jackett because support for magnet links were added.
In case a tracker doesn't provide normal torrent files and they're only available from the torrent's details page a request to the jackett download link will return a redirect (HTTP status code 301, Moved Permanently) with the Location header set to a magnet URI.
Not sure if sickrage can handle this case. This is used by e.g. the jackett ETTV and Torrent Downloads indexers.

**Comment by cpainchaud** [comment]
+1 I am having the same issue.

**Comment by cpainchaud** [comment]
This is how they fixed it at Medusa:

https://github.com/pymedusa/Medusa/commit/f91e7a366cc140c97abf81aaed9269d54e1b85e3

**Comment by miigotu** [comment]
Not concerned with how it was fixed elsewhere

**Comment by miigotu** [comment]
Check if it is fixed on the develop branch please, Thanks.

**Comment by cpainchaud** [comment]
#4152 did not fix it for me as it's still naming the file with .nzb extension:
2017-11-24 14:40:47 INFO SEARCHQUEUE-MANUAL-328711 :: Saved result to Star.Trek.Discovery.S01E08.HDTV.FRENCH.nzb
2017-11-24 14:40:44 INFO SEARCHQUEUE-MANUAL-328711 :: Downloading a result from JAcket_NextTorrent at http://localhost:9117/dl/nexttorrent/?jackett_apikey=etj7zhkszaxt2n1fks50sf2s4m9v3sd6&path=aStCLytnZW12VTNyQzI2NUV6NXFwZGJjWVBNa0xZR2s3cVZMdVpoWkFKcjRGQnF5bWlPbDJWcFpRcDV1NWJ4dnlrWVFTWHE4QUlzY3JZUXFGZSs0MFhDT2lxdEVCZzg1VHc1bE96Q1U2Z2ZnUWhGclY0b0lJdDE3Mm9oKzAwelR6ek1TM3F6dnZOSmk1NHFXTkdqdDdFc21JNE5NYWc2K0pEd2tsNVRWMUhJTUF6N29BZHdTejY3cWhxY1JEN1dYUmhTMUtlcWtKWDdaaGdKY1ZGamZLNG1OMXJSblJUQ0RIRHFLRjkvSjcveXZ0UEk0QW1WSnI5dE5BQ0QySWdtSFN6dUFaZjZGYXhjK3pWc1YyRkFQQkZtdWxlMCs1T3NPRWpjRFhuOFpkOWxhL2xFVnVUNXJtano0aTM4VWY4ZTNWemxlYi8wSklOKzB5NUtYaTh5UXY3V0Y2SHZRQXlJWitmSDVXbG5EUFhoVUc5QjlzaU1pN3ZQMEJISTZtMENB0&file=Star+Trek+Discovery+S01E08+HDTV+FRENCH+
2017-11-24 14:40:44 INFO SEARCHQUEUE-MANUAL-328711 :: Downloading Star.Trek.Discovery.S01E08.HDTV.FRENCH from JAcket_NextTorrent

**Comment by miigotu** [comment]
i guess i will have to install jackett and test it while I change it, but my change should have fixed it according to https://github.com/SickRage/SickRage/issues/4132#issuecomment-344009629

**Comment by cpainchaud** [comment]
To give you more insight : 

- your change effectively changes the file name : it will save it as a .torrent file
- unfortunately the caller function doesn't know about the new filename , so logs are showing the original filename.
- since filename change is not propagated to caller functionsl, some post processing is ignored, in my case it's about sending file to TRANSMISSION that is not occuring anymore from what I can judge.

**Comment by miigotu** [comment]
makes sens @cpainchaud , ill get it fixed soon enough

**Comment by maxcore** [comment]
😃😃

**Comment by kaso17** [comment]
@miigotu this apparently already has been fixed on the medusa fork.
Not sure how in sync the relevant code is, relevant PRs:
https://github.com/pymedusa/Medusa/pull/3153/files
https://github.com/pymedusa/Medusa/pull/3214/files

**Comment by miigotu** [comment]
Stop linking to competing forks.

**Comment by miigotu** [comment]
@maxcore please remove the comment on Jackett/Jackett that references this issue (and leads users to a different fork)

Also, I'm merging my fix into develop soon, please test.

**Comment by maxcore** [comment]
@miigotu i have remove my comment 

the dev work for me thx !

**Comment by n0ncetonic** [comment]
Just wondering if this was ever fixed

**Comment by miigotu** [comment]
Yes, 8 months ago.

**Comment by jangrewe** [comment]
I think something broke this again, as SickChill _snatches_ loads of episodes from Cardigann, but nothing ever shows up in Deluge (or SABnzbd) for a couple of days now.

I had a look in the logs and noticed this:
```
2018-12-15 12:31:31 INFO     SEARCHQUEUE-BACKLOG-153021 :: Downloading <something>.WEBRip.x264-PBS[ettv] from Cardigann
2018-12-15 12:31:31 INFO     SEARCHQUEUE-BACKLOG-153021 :: Sending NZB to SABnzbd
```
Be assured that my setup ran flawless before, i haven't touched anything recently...
